### ISSUE TITLE
Test builds report incorrect version `0.1.0`

### ISSUE THREAD

**Issue by gnidan** [dappnode/DAppNodePackage-erigon#18]
**Describe the bug**

This repository is configured to publish test builds to IPFS upon pull requests. These test builds use version 0.1.0 rather than a proper prerelease version (e.g. `0.1.7-0`). This makes it hard to test, since the DappNode manager software will interpret the test build as a downgrade, and thus it won't match a production release.

**To Reproduce**

1. Install latest released DNP (which is greater than v0.1.0)
2. Open a PR here
3. Install the test build
4. Observe incorrect version

**Expected behavior**

Test builds should increment the patch release and use a prerelease identifier (e.g. if the latest is `0.1.7`, the prerelease should be `0.1.8-0`, or if there's already a `0.1.8-0`, the test build should be `0.1.7-1`)

**Screenshots**

This is wrong:

<img width="1278" alt="Screen Shot 2021-08-19 at 13 23 03" src="https://user-images.githubusercontent.com/151065/130115036-bdc1af3a-1208-478c-866f-407f8e92ce29.png">

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by alexpeterson91** [comment]
Doing that would require a new tag and a new pin for each hash created by each PR or commit, it would not be easy to manage and would decrease productivity immensely and make it so that we'd probably have to lock first time contributors and even most non team and officially named contributors from being able to open PRs on our repos, we'd have to require them fork it and restrict access to our CI.  None of those things are what we want.  So when you build your own testing release versions or our own make sure to just change the version to the same version as currently published, so then you get no warnings and auto update wont interfere until a new version is published, and then itll update to the officially signed latest release.  As one of the teams most prolific and head testers, I'm very used to this as when im developing myself in VS code i could be publishing 5 versions an hour to IPFS and only pin the one that works. so i change the dappnode version in the manifest to the current published version and have no issues being prompted to downgrade, downgrading by choice, or with auto update updating to the next version, likely the version im already using, just official and signed also with the latest tag updating my version.
